//OPTION
export const CHANGE_OPTIONS = 'CHANGE_OPTIONS'
export const CHANGE_COMMENT_OPTIONS = 'CHANGE_COMMENT_OPTIONS'

export const ADD_ARTICLE_LIST = 'ADD_ARTICLE_LIST'
export const REQUEST_ARTICLE_LIST = 'REQUEST_ARTICLE_LIST'
export const GET_CAPTCHAURL = 'GET_CAPTCHAURL'

export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const GET_USERINFO = 'GET_USERINFO'
export const GET_USERINFO_SUCCESS = 'GET_USERINFO_SUCCESS'
export const GET_USERINFO_FAILURE = 'GET_USERINFO_FAILURE'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const GET_INDEX_IMG = 'GET_INDEX_IMG'
export const GET_INDEX_IMG_REQUEST = 'GET_INDEX_IMG_REQUEST'
export const GET_INDEX_IMG_SUCCESS = 'GET_INDEX_IMG_SUCCESS'
export const GET_INDEX_IMG_FAILURE = 'GET_INDEX_IMG_FAILURE'


//ARTICLE
export const ARTICLE_LIST = 'ARTICLE_LIST'
export const ARTICLE_LIST_REQUEST = 'ARTICLE_LIST_REQUEST'
export const ARTICLE_LIST_SUCCESS = 'ARTICLE_LIST_SUCCESS'
export const ARTICLE_LIST_FAILURE = 'ARTICLE_LIST_FAILURE'
export const POST_LIST = 'POST_LIST'
export const POST_LIST_REQUEST = 'POST_LIST_REQUEST'
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS'
export const POST_LIST_FAILURE = 'POST_LIST_FAILURE'
export const VIDEO_LIST = 'VIDEO_LIST'
export const VIDEO_LIST_REQUEST = 'VIDEO_LIST_REQUEST'
export const VIDEO_LIST_SUCCESS = 'VIDEO_LIST_SUCCESS'
export const VIDEO_LIST_FAILURE = 'VIDEO_LIST_FAILURE'
export const DOC_LIST = 'DOC_LIST'
export const DOC_LIST_REQUEST = 'DOC_LIST_REQUEST'
export const DOC_LIST_SUCCESS = 'DOC_LIST_SUCCESS'
export const DOC_LIST_FAILURE = 'DOC_LIST_FAILURE'
export const QUESTION_LIST = 'QUESTION_LIST'
export const QUESTION_LIST_REQUEST = 'QUESTION_LIST_REQUEST'
export const QUESTION_LIST_SUCCESS = 'QUESTION_LIST_SUCCESS'
export const QUESTION_LIST_FAILURE = 'QUESTION_LIST_FAILURE'
export const BOOK_LIST = 'BOOK_LIST'
export const BOOK_LIST_REQUEST = 'BOOK_LIST_REQUEST'
export const BOOK_LIST_SUCCESS = 'BOOK_LIST_SUCCESS'
export const BOOK_LIST_FAILURE = 'BOOK_LIST_FAILURE'
export const TED_LIST = 'TED_LIST'
export const TED_LIST_REQUEST = 'TED_LIST_REQUEST'
export const TED_LIST_SUCCESS = 'TED_LIST_SUCCESS'
export const TED_LIST_FAILURE = 'TED_LIST_FAILURE'

export const HOT_VIDEO_LIST = 'HOT_VIDEO_LIST'
export const HOT_VIDEO_LIST_REQUEST = 'HOT_VIDEO_LIST_REQUEST'
export const HOT_VIDEO_LIST_SUCCESS = 'HOT_VIDEO_LIST_SUCCESS'
export const HOT_VIDEO_LIST_FAILURE = 'HOT_VIDEO_LIST_FAILURE'
export const HOT_DOC_LIST = 'HOT_DOC_LIST'
export const HOT_DOC_LIST_REQUEST = 'HOT_DOC_LIST_REQUEST'
export const HOT_DOC_LIST_SUCCESS = 'HOT_DOC_LIST_SUCCESS'
export const HOT_DOC_LIST_FAILURE = 'HOT_DOC_LIST_FAILURE'

export const WEEK_HOT_LIST = 'WEEK_HOT_LIST'
export const WEEK_HOT_LIST_REQUEST = 'WEEK_HOT_LIST_REQUEST'
export const WEEK_HOT_LIST_SUCCESS = 'WEEK_HOT_LIST_SUCCESS'
export const WEEK_HOT_LIST_FAILURE = 'WEEK_HOT_LIST_FAILURE'
export const MONTH_HOT_LIST = 'MONTH_HOT_LIST'
export const MONTH_HOT_LIST_REQUEST = 'MONTH_HOT_LIST_REQUEST'
export const MONTH_HOT_LIST_SUCCESS = 'MONTH_HOT_LIST_SUCCESS'
export const MONTH_HOT_LIST_FAILURE = 'MONTH_HOT_LIST_FAILURE'

export const ARTICLE_DETAIL = 'ARTICLE_DETAIL'
export const ARTICLE_DETAIL_REQUEST = 'ARTICLE_DETAIL_REQUEST'
export const ARTICLE_DETAIL_SUCCESS = 'ARTICLE_DETAIL_SUCCESS'
export const ARTICLE_DETAIL_FAILURE = 'ARTICLE_DETAIL_FAILURE'
export const ADD_ARTICLE_SUCCESS = 'ADD_ARTICLE_SUCCESS'
export const CHANGE_ARTICLE_DESC = 'CHANGE_ARTICLE_DESC'


//COMMENT
export const COMMENT_LIST = 'COMMENT_LIST'
export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST'
export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS'
export const COMMENT_LIST_FAILURE = 'COMMENT_LIST_FAILURE'
export const COMMENT_DETAIL = 'COMMENT_DETAIL'
export const COMMENT_DETAIL_REQUEST = 'COMMENT_DETAIL_REQUEST'
export const COMMENT_DETAIL_SUCCESS = 'COMMENT_DETAIL_SUCCESS'
export const COMMENT_DETAIL_FAILURE = 'COMMENT_DETAIL_FAILURE'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_REPLY_SUCCESS = 'ADD_REPLY_SUCCESS'

//USER
export const USER_LIST = 'USER_LIST'
export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAILURE = 'USER_LIST_FAILURE'
export const USER_DETAIL = 'USER_DETAIL'
export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST'
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS'
export const USER_DETAIL_FAILURE = 'USER_DETAIL_FAILURE'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'

//MESSAGE
export const MESSAGE_LIST = 'MESSAGE_LIST'
export const MESSAGE_LIST_REQUEST = 'MESSAGE_LIST_REQUEST'
export const MESSAGE_LIST_SUCCESS = 'MESSAGE_LIST_SUCCESS'
export const MESSAGE_LIST_FAILURE = 'MESSAGE_LIST_FAILURE'
export const MESSAGE_DETAIL = 'MESSAGE_DETAIL'
export const MESSAGE_DETAIL_REQUEST = 'MESSAGE_DETAIL_REQUEST'
export const MESSAGE_DETAIL_SUCCESS = 'MESSAGE_DETAIL_SUCCESS'
export const MESSAGE_DETAIL_FAILURE = 'MESSAGE_DETAIL_FAILURE'
export const UNREAD_MESSAGE_COUNT = 'UNREAD_MESSAGE_COUNT'
export const UNREAD_MESSAGE_COUNT_FAILURE = 'UNREAD_MESSAGE_COUNT_FAILURE'


// TOPIC
export const TOPIC_LIST = 'TOPIC_LIST'
export const TOPIC_LIST_REQUEST = 'TOPIC_LIST_REQUEST'
export const TOPIC_LIST_SUCCESS = 'TOPIC_LIST_SUCCESS'
export const TOPIC_LIST_FAILURE = 'TOPIC_LIST_FAILURE'
export const TOPIC_DETAIL = 'TOPIC_DETAIL'
export const TOPIC_DETAIL_REQUEST = 'TOPIC_DETAIL_REQUEST'
export const TOPIC_DETAIL_SUCCESS = 'TOPIC_DETAIL_SUCCESS'
export const TOPIC_DETAIL_FAILURE = 'TOPIC_DETAIL_FAILURE'
export const ADD_TOPIC_SUCCESS = 'ADD_TOPIC_SUCCESS'



// ORDER
export const ORDER_LIST = 'ORDER_LIST'
export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAILURE = 'ORDER_LIST_FAILURE'
export const ORDER_DETAIL = 'ORDER_DETAIL'
export const TORDER_DETAIL_REQUEST = 'TORDER_DETAIL_REQUEST'
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS'
export const ORDER_DETAIL_FAILURE = 'ORDER_DETAIL_FAILURE'
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS'


// IMAGE
export const SKILLMAP_LIST = 'SKILLMAP_LIST'
export const SKILLMAP_LIST_REQUEST = 'SKILLMAP_LIST_REQUEST'
export const SKILLMAP_LIST_SUCCESS = 'SKILLMAP_LIST_SUCCESS'
export const SKILLMAP_LIST_FAILURE = 'SKILLMAP_LIST_FAILURE'


export const TOGGLE_TOPIC_LIKE = 'TOGGLE_TOPIC_LIKE'
export const TOGGLE_TOPIC_LIKE_REQUEST = 'TOGGLE_TOPIC_LIKE_REQUEST'
export const TOGGLE_TOPIC_LIKE_SUCCESS = 'TOGGLE_TOPIC_LIKE_SUCCESS'
export const TOGGLE_TOPIC_LIKE_FAILURE = 'TOGGLE_TOPIC_LIKE_FAILURE'

export const TOGGLE_ARTICLE_LIKE = 'TOGGLE_ARTICLE_LIKE'
export const TOGGLE_ARTICLE_LIKE_REQUEST = 'TOGGLE_ARTICLE_LIKE_REQUEST'
export const TOGGLE_ARTICLE_LIKE_SUCCESS = 'TOGGLE_ARTICLE_LIKE_SUCCESS'
export const TOGGLE_ARTICLE_LIKE_FAILURE = 'TOGGLE_ARTICLE_LIKE_FAILURE'


//Tag
export const TAG_LIST = 'TAG_LIST'
export const TAG_LIST_REQUEST = 'TAG_LIST_REQUEST'
export const TAG_LIST_SUCCESS = 'TAG_LIST_SUCCESS'
export const TAG_LIST_FAILURE = 'TAG_LIST_FAILURE'
export const TAG_DETAIL_SUCCESS = 'TAG_DETAIL_SUCCESS'
export const TAG_DETAIL_FAILURE = 'TAG_DETAIL_FAILURE'
export const ADD_TAG_SUCCESS = 'ADD_TAG_SUCCESS'

// FEED_POST

export const RENCENT_POST_LIST = 'RENCENT_POST_LIST'
export const RENCENT_POST_LIST_REQUEST = 'RENCENT_POST_LIST_REQUEST'
export const RENCENT_POST_LIST_SUCCESS = 'RENCENT_POST_LIST_SUCCESS'
export const RENCENT_POST_LIST_FAILURE = 'RENCENT_POST_LIST_FAILURE'

export const FEED_POST_LIST = 'FEED_POST_LIST'
export const FEED_POST_LIST_REQUEST = 'FEED_POST_LIST_REQUEST'
export const FEED_POST_LIST_SUCCESS = 'FEED_POST_LIST_SUCCESS'
export const FEED_POST_LIST_FAILURE = 'FEED_POST_LIST_FAILURE'

export const TOGGLE_POST_READED = 'TOGGLE_POST_READED'
export const TOGGLE_POST_READED_REQUEST = 'TOGGLE_POST_READED_REQUEST'
export const TOGGLE_POST_READED_SUCCESS = 'TOGGLE_POST_READED_SUCCESS'
export const TOGGLE_POST_READED_FAILURE = 'TOGGLE_POST_READED_FAILURE'

//FEED
export const MY_FEEDS = 'MY_FEEDS'
export const MY_FEEDS_REQUEST = 'MY_FEEDS_REQUEST'
export const MY_FEEDS_SUCCESS = 'MY_FEEDS_SUCCESS'
export const MY_FEEDS_FAILURE = 'MY_FEEDS_FAILURE'

export const FEEDS_LIST = 'FEEDS_LIST'
export const FEEDS_LIST_REQUEST = 'FEEDS_LIST_REQUEST'
export const FEEDS_LIST_SUCCESS = 'FEEDS_LIST_SUCCESS'
export const FEEDS_LIST_FAILURE = 'FEEDS_LIST_FAILURE'

export const FEED_DETAIL = 'FEED_DETAIL'
export const FEED_DETAIL_REQUEST = 'FEED_DETAIL_REQUEST'
export const FEED_DETAIL_SUCCESS = 'FEED_DETAIL_SUCCESS'
export const FEED_DETAIL_FAILURE = 'FEED_DETAIL_FAILURE'


export const GET_APPS = 'GET_APPS'
export const GET_APPS_SUCCESS = 'GET_APPS_SUCCESS'
export const GET_APPS_FAILURE = 'GET_APPS_FAILURE'
export const GET_APPS_REQUEST = 'GET_APPS_REQUEST'

export const GET_SNSLOGINS = 'GET_SNSLOGINS'
export const GET_SNSLOGINS_SUCCESS = 'GET_SNSLOGINS_SUCCESS'
export const GET_SNSLOGINS_FAILURE = 'GET_SNSLOGINS_FAILURE'

export const SHOW_MSG = 'SHOW_MSG'
export const HIDE_MSG = 'HIDE_MSG'